version: '2'
services:
    jhipstersampleapplication1-app:
        image: jhipstersampleapplication1
        environment:
            - _JAVA_OPTIONS=-Xmx512m -Xms256m
            - SPRING_PROFILES_ACTIVE=prod,swagger
            - SPRING_DATASOURCE_URL=jdbc:sqlserver://jhipstersampleapplication1-mssql:1433;database=jhipsterSampleApplication1
            - JHIPSTER_SLEEP=10 # gives time for the database to boot before the application
        ports:
            - 8080:8080
    jhipstersampleapplication1-mssql:
        extends:
            file: mssql.yml
            service: jhipstersampleapplication1-mssql
